package com.alexan.findevents.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.alexan.findevents.dao.DBEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DBEVENT.
*/
public class DBEventDao extends AbstractDao<DBEvent, Long> {

    public static final String TABLENAME = "DBEVENT";

    /**
     * Properties of entity DBEvent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserID = new Property(1, Long.class, "userID", false, "USER_ID");
        public final static Property LocationID = new Property(2, Long.class, "locationID", false, "LOCATION_ID");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Description = new Property(4, String.class, "description", false, "DESCRIPTION");
        public final static Property Address = new Property(5, String.class, "address", false, "ADDRESS");
        public final static Property Province = new Property(6, String.class, "province", false, "PROVINCE");
        public final static Property City = new Property(7, String.class, "city", false, "CITY");
        public final static Property District = new Property(8, String.class, "district", false, "DISTRICT");
        public final static Property Addressdetail = new Property(9, String.class, "addressdetail", false, "ADDRESSDETAIL");
        public final static Property Startt = new Property(10, String.class, "startt", false, "STARTT");
        public final static Property Endt = new Property(11, String.class, "endt", false, "ENDT");
        public final static Property Startd = new Property(12, String.class, "startd", false, "STARTD");
        public final static Property Endd = new Property(13, String.class, "endd", false, "ENDD");
        public final static Property CollectionNum = new Property(14, Integer.class, "collectionNum", false, "COLLECTION_NUM");
        public final static Property AttendNum = new Property(15, Integer.class, "attendNum", false, "ATTEND_NUM");
        public final static Property CommentNum = new Property(16, Integer.class, "commentNum", false, "COMMENT_NUM");
        public final static Property Timestamp = new Property(17, Long.class, "timestamp", false, "TIMESTAMP");
        public final static Property Visibility = new Property(18, Long.class, "visibility", false, "VISIBILITY");
        public final static Property Starttime = new Property(19, Long.class, "starttime", false, "STARTTIME");
        public final static Property Endtime = new Property(20, Long.class, "endtime", false, "ENDTIME");
    };

    private DaoSession daoSession;


    public DBEventDao(DaoConfig config) {
        super(config);
    }
    
    public DBEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DBEVENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'USER_ID' INTEGER," + // 1: userID
                "'LOCATION_ID' INTEGER," + // 2: locationID
                "'TITLE' TEXT," + // 3: title
                "'DESCRIPTION' TEXT," + // 4: description
                "'ADDRESS' TEXT," + // 5: address
                "'PROVINCE' TEXT," + // 6: province
                "'CITY' TEXT," + // 7: city
                "'DISTRICT' TEXT," + // 8: district
                "'ADDRESSDETAIL' TEXT," + // 9: addressdetail
                "'STARTT' TEXT," + // 10: startt
                "'ENDT' TEXT," + // 11: endt
                "'STARTD' TEXT," + // 12: startd
                "'ENDD' TEXT," + // 13: endd
                "'COLLECTION_NUM' INTEGER," + // 14: collectionNum
                "'ATTEND_NUM' INTEGER," + // 15: attendNum
                "'COMMENT_NUM' INTEGER," + // 16: commentNum
                "'TIMESTAMP' INTEGER," + // 17: timestamp
                "'VISIBILITY' INTEGER," + // 18: visibility
                "'STARTTIME' INTEGER," + // 19: starttime
                "'ENDTIME' INTEGER);"); // 20: endtime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DBEVENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userID = entity.getUserID();
        if (userID != null) {
            stmt.bindLong(2, userID);
        }
 
        Long locationID = entity.getLocationID();
        if (locationID != null) {
            stmt.bindLong(3, locationID);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(5, description);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(6, address);
        }
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(7, province);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(8, city);
        }
 
        String district = entity.getDistrict();
        if (district != null) {
            stmt.bindString(9, district);
        }
 
        String addressdetail = entity.getAddressdetail();
        if (addressdetail != null) {
            stmt.bindString(10, addressdetail);
        }
 
        String startt = entity.getStartt();
        if (startt != null) {
            stmt.bindString(11, startt);
        }
 
        String endt = entity.getEndt();
        if (endt != null) {
            stmt.bindString(12, endt);
        }
 
        String startd = entity.getStartd();
        if (startd != null) {
            stmt.bindString(13, startd);
        }
 
        String endd = entity.getEndd();
        if (endd != null) {
            stmt.bindString(14, endd);
        }
 
        Integer collectionNum = entity.getCollectionNum();
        if (collectionNum != null) {
            stmt.bindLong(15, collectionNum);
        }
 
        Integer attendNum = entity.getAttendNum();
        if (attendNum != null) {
            stmt.bindLong(16, attendNum);
        }
 
        Integer commentNum = entity.getCommentNum();
        if (commentNum != null) {
            stmt.bindLong(17, commentNum);
        }
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(18, timestamp);
        }
 
        Long visibility = entity.getVisibility();
        if (visibility != null) {
            stmt.bindLong(19, visibility);
        }
 
        Long starttime = entity.getStarttime();
        if (starttime != null) {
            stmt.bindLong(20, starttime);
        }
 
        Long endtime = entity.getEndtime();
        if (endtime != null) {
            stmt.bindLong(21, endtime);
        }
    }

    @Override
    protected void attachEntity(DBEvent entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBEvent readEntity(Cursor cursor, int offset) {
        DBEvent entity = new DBEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // userID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // locationID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // description
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // address
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // province
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // city
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // district
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // addressdetail
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // startt
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // endt
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // startd
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // endd
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // collectionNum
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15), // attendNum
            cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16), // commentNum
            cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17), // timestamp
            cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18), // visibility
            cursor.isNull(offset + 19) ? null : cursor.getLong(offset + 19), // starttime
            cursor.isNull(offset + 20) ? null : cursor.getLong(offset + 20) // endtime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLocationID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDescription(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddress(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setProvince(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCity(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDistrict(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAddressdetail(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setStartt(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setEndt(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setStartd(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setEndd(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCollectionNum(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setAttendNum(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
        entity.setCommentNum(cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16));
        entity.setTimestamp(cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17));
        entity.setVisibility(cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18));
        entity.setStarttime(cursor.isNull(offset + 19) ? null : cursor.getLong(offset + 19));
        entity.setEndtime(cursor.isNull(offset + 20) ? null : cursor.getLong(offset + 20));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
