package com.alexan.findevents.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.alexan.findevents.dao.DBGroupFriend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DBGROUP_FRIEND.
*/
public class DBGroupFriendDao extends AbstractDao<DBGroupFriend, Long> {

    public static final String TABLENAME = "DBGROUP_FRIEND";

    /**
     * Properties of entity DBGroupFriend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property GroupID = new Property(1, long.class, "groupID", false, "GROUP_ID");
        public final static Property FriendID = new Property(2, long.class, "friendID", false, "FRIEND_ID");
    };

    private DaoSession daoSession;

    private Query<DBGroupFriend> dBPerson_ThegroupsQuery;
    private Query<DBGroupFriend> dBGroup_ThefriendsQuery;

    public DBGroupFriendDao(DaoConfig config) {
        super(config);
    }
    
    public DBGroupFriendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DBGROUP_FRIEND' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'GROUP_ID' INTEGER NOT NULL ," + // 1: groupID
                "'FRIEND_ID' INTEGER NOT NULL );"); // 2: friendID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DBGROUP_FRIEND'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBGroupFriend entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getGroupID());
        stmt.bindLong(3, entity.getFriendID());
    }

    @Override
    protected void attachEntity(DBGroupFriend entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBGroupFriend readEntity(Cursor cursor, int offset) {
        DBGroupFriend entity = new DBGroupFriend( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // groupID
            cursor.getLong(offset + 2) // friendID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBGroupFriend entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGroupID(cursor.getLong(offset + 1));
        entity.setFriendID(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBGroupFriend entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBGroupFriend entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "thegroups" to-many relationship of DBPerson. */
    public List<DBGroupFriend> _queryDBPerson_Thegroups(long friendID) {
        synchronized (this) {
            if (dBPerson_ThegroupsQuery == null) {
                QueryBuilder<DBGroupFriend> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FriendID.eq(null));
                dBPerson_ThegroupsQuery = queryBuilder.build();
            }
        }
        Query<DBGroupFriend> query = dBPerson_ThegroupsQuery.forCurrentThread();
        query.setParameter(0, friendID);
        return query.list();
    }

    /** Internal query to resolve the "thefriends" to-many relationship of DBGroup. */
    public List<DBGroupFriend> _queryDBGroup_Thefriends(long groupID) {
        synchronized (this) {
            if (dBGroup_ThefriendsQuery == null) {
                QueryBuilder<DBGroupFriend> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GroupID.eq(null));
                dBGroup_ThefriendsQuery = queryBuilder.build();
            }
        }
        Query<DBGroupFriend> query = dBGroup_ThefriendsQuery.forCurrentThread();
        query.setParameter(0, groupID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDBPersonDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getDBGroupDao().getAllColumns());
            builder.append(" FROM DBGROUP_FRIEND T");
            builder.append(" LEFT JOIN DBPERSON T0 ON T.'FRIEND_ID'=T0.'_id'");
            builder.append(" LEFT JOIN DBGROUP T1 ON T.'GROUP_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DBGroupFriend loadCurrentDeep(Cursor cursor, boolean lock) {
        DBGroupFriend entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DBPerson friends = loadCurrentOther(daoSession.getDBPersonDao(), cursor, offset);
         if(friends != null) {
            entity.setFriends(friends);
        }
        offset += daoSession.getDBPersonDao().getAllColumns().length;

        DBGroup groups = loadCurrentOther(daoSession.getDBGroupDao(), cursor, offset);
         if(groups != null) {
            entity.setGroups(groups);
        }

        return entity;    
    }

    public DBGroupFriend loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DBGroupFriend> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DBGroupFriend> list = new ArrayList<DBGroupFriend>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DBGroupFriend> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DBGroupFriend> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
